### PR TITLE
Split project

### PR DESCRIPTION
**Pull request by malteserteresa**

### CODE REVIEW

**Comment by MikeJohnPage** [comment]
Why did you decide to move away from conda?

**Comment by malteserteresa** [comment]
Tensorflow 2.0 isn't available on conda yet

**Comment by MikeJohnPage** [comment]
Everything executes fine except the Docker. A local Docker instance will need installing on local machines, correct? Currently the requirements file and installation docs don't cover this.

**Comment by malteserteresa** [comment]
I edited the readme to ignore the dockerfile. That will do til I get more
time to fix it

**Pull request merged**
